#!/bin/bash

while getopts ":q:l:p:d:" opt; do
  case $opt in
    q) QUARTER=$OPTARG;;
    p) POOL=$OPTARG;;
    d) DATASHEET=$OPTARG;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

for i in {1..4}; do
  quarterlane -q $QUARTER -l $i -p $POOL -d $DATASHEET
done
