#!/bin/bash

LIMS_PARENT="/gale/oberon/data1/lims"

usage() {
echo "eg, samplesheet-lane -p mCT_NOME_E14GM -d hic-methylome::libraries.DataSheet -l 1 -m n"
echo "-p, pool name"
echo "-d, datasheet"
echo "-l, lane number"
echo "-m, (y/n) if miseq sample sheet"
echo "-h, display this help message"
}

while getopts ":p:d:l:m:h" opt; do
  case $opt in
    p) POOL=$OPTARG;;
    d) DATASHEET=$OPTARG;;
    l) LANE=$OPTARG;;
    m) MISEQ=$OPTARG;;
    h) usage;;
  esac
done

datasheet="$LIMS_PARENT/$DATASHEET"

case "$MISEQ" in
  y) grep -a $POOL $datasheet | awk '{FS = "\t"; print $18 ",," $2 ",,," $19 ",," $20 "," $21 "," $30}'
    ;;
  n) grep -a $POOL $datasheet | awk -v lane="$LANE" '{FS = "\t"; print lane "," $18 ",," $2 ",,," $19 ",," $20 "," $21 "," $30}'
    ;;
esac
